### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/docker-lvmpy#156]
* PRD: SYSTEM UPGRADE

Docker-lvmpy should be packaged to binary to avoid dependency issues. Docker-lvmpy has some dependencies that work only for python3.6 which is default for Ubuntu 18.04, but are deprecated for Ubuntu 22.04. It should be distributed as binary to avoid such compatibility issues.

UPD: upgrade to Ubuntu 20.04

**Comment by OleksanderSalamatov** [comment]
Verified
Node-cli: 2.3.0-beta.1
Ubuntu: 18.04, 20.04
Testrail: C10, C26 in Schain project

Lvmpy now hardcoded in node-cli
Schain volumes management is working correctly during schain creation/remove both on 18.04 and 20.04 Ubuntu versions
